name: 'ColdFusion/core'
author: 'ChainFuse'
description: 'TODO'
inputs:
  token:
    description: Used to pull node distributions from ollama. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  ollama-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0. See https://github.com/ollama/ollama/releases for the latest releases.'
    default: 0.x
  os:
    description: 'INTERNAL: DO NOT TOUCH'
    default: ${{ runner.os }}
  arch:
    description: 'INTERNAL: DO NOT TOUCH'
    default: ${{ runner.arch }}
  check-latest:
    description: 'Set this option if you want the action to check for the latest available version of ollama that satisfies the version spec.'
    deprecationMessage: 'Not yet implemented'
    default: false
  model:
    description: Model to run against. See https://ollama.com/library
    required: true
    default: llama3.1
  cache:
    description: 'Set this option to true to enable caching of models.'
    default: true
  modelDir:
    description: Location to download model. Sub folders for each model will be automatically created
    default: ${{ runner.temp }}/ColdFusion/models
outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit.'
  ollama-version:
    description: 'The installed ollama version.'
runs:
  using: 'node20'
  pre: 'dist/pre/index.js'
  # pre-if:
  main: 'dist/main/index.js'
  post-if: success()
  post: 'dist/post/index.js'
branding:
  color: 'blue'
  icon: 'cloud-off'
