name: 'ColdFusion/core'
author: 'ChainFuse'
description: 'TODO'
inputs:
  model:
    description: Model to run against. Expects full model name (`-GGUF` prefix optional). Downloads from https://huggingface.co/TheBloke?search_models=GGUF
    required: true
    default: TheBloke/Mixtral_7Bx2_MoE
  quantMethod:
    description: The quantitative analysis approach for evaluating AI models, using statistical and mathematical techniques to assess their effectiveness and suitability for specific tasks
    required: true
    default: Q2_K
  modelDir:
    description: Location to download model
    required: true
    default: ${{ github.repository }}
# outputs:
runs:
  using: 'node20'
  pre: 'dist/pre/index.js'
  # pre-if:
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  # post-if:
branding:
  color: 'blue'
  icon: 'cloud-off'
