name: Compile, Test, and Publish

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
      - 'test/**'
      - 'action.yml'
      - 'package*.json'
      - 'tsconfig.json'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: dist
          path: ${{ github.workspace }}/dist
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
  test:
    needs: ['compile']
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
  publish:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Delete old compiled action
        run: rm -rv dist
        shell: bash
      - uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
        with:
          name: dist
          path: ${{ github.workspace }}/dist
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add dist/
      - run: git commit -m "[ci skip] $PREVIOUS_GIT_MESSAGE"
        shell: bash
        env:
          PREVIOUS_GIT_MESSAGE: ${{ github.event.head_commit.message }}
      - run: git push
